// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	civil "cloud.google.com/go/civil"
	response "kompass/internal/controller/http/v1/response"
	entity "kompass/internal/entity"
)

type TransportationConverterImpl struct{}

func (c *TransportationConverterImpl) ConvertAllTransportation(source []entity.Transportation) []response.Transportation {
	var responseTransportationList []response.Transportation
	if source != nil {
		responseTransportationList = make([]response.Transportation, len(source))
		for i := 0; i < len(source); i++ {
			responseTransportationList[i] = c.ConvertTransportation(source[i])
		}
	}
	return responseTransportationList
}
func (c *TransportationConverterImpl) ConvertTransportation(source entity.Transportation) response.Transportation {
	var responseTransportation response.Transportation
	responseTransportation.ID = source.ID
	responseTransportation.TripID = source.TripID
	responseTransportation.Type = string(source.Type)
	responseTransportation.Origin = c.entityLocationToEntityLocation(source.Origin)
	responseTransportation.Destination = c.entityLocationToEntityLocation(source.Destination)
	responseTransportation.DepartureDateTime = c.civilDateTimeToCivilDateTime(source.DepartureDateTime)
	responseTransportation.ArrivalDateTime = c.civilDateTimeToCivilDateTime(source.ArrivalDateTime)
	responseTransportation.GeoJson = source.GeoJson
	responseTransportation.Price = source.Price
	responseTransportation.FlightDetail = source.FlightDetail
	responseTransportation.TrainDetail = source.TrainDetail
	return responseTransportation
}
func (c *TransportationConverterImpl) civilDateTimeToCivilDateTime(source civil.DateTime) civil.DateTime {
	return source
}
func (c *TransportationConverterImpl) entityLocationToEntityLocation(source entity.Location) entity.Location {
	return source
}

type TripConverterImpl struct{}

func (c *TripConverterImpl) ConvertTrip(source entity.Trip) response.Trip {
	var responseTrip response.Trip
	responseTrip.ID = source.ID
	responseTrip.Name = source.Name
	responseTrip.StartDate = c.civilDateToCivilDate(source.StartDate)
	responseTrip.EndDate = c.civilDateToCivilDate(source.EndDate)
	responseTrip.Description = source.Description
	responseTrip.ImageUrl = source.ImageUrl
	return responseTrip
}
func (c *TripConverterImpl) ConvertTrips(source []entity.Trip) []response.Trip {
	var responseTripList []response.Trip
	if source != nil {
		responseTripList = make([]response.Trip, len(source))
		for i := 0; i < len(source); i++ {
			responseTripList[i] = c.ConvertTrip(source[i])
		}
	}
	return responseTripList
}
func (c *TripConverterImpl) civilDateToCivilDate(source civil.Date) civil.Date {
	return source
}
