services:
  db:
    container_name: db
    image: postgres:17-alpine
    environment:
      POSTGRES_SSL_MODE: "disable"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "myAwEsOm3pa55@w0rd"
      POSTGRES_USER: "user"
#    volumes:
#      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#volumes:
#  db_data: