// Code generated by ogen, DO NOT EDIT.
package api

type GetLocationRes interface {
	getLocationRes()
}

type GetTrainStationRes interface {
	getTrainStationRes()
}

type PostFlightRes interface {
	postFlightRes()
}

type PostTrainJourneyRes interface {
	postTrainJourneyRes()
}
