// Code generated by ogen, DO NOT EDIT.

package api

// DeleteAccommodationParams is parameters of deleteAccommodation operation.
type DeleteAccommodationParams struct {
	// Trip ID.
	TripID int
	// Accommodation ID.
	AccommodationID int
}

// DeleteActivityParams is parameters of deleteActivity operation.
type DeleteActivityParams struct {
	// Trip ID.
	TripID int
	// Activity ID.
	ActivityID int
}

// DeleteAttachmentParams is parameters of deleteAttachment operation.
type DeleteAttachmentParams struct {
	// Trip ID.
	TripID int
	// Attachment ID.
	AttachmentID int
}

// DeleteTransportationParams is parameters of deleteTransportation operation.
type DeleteTransportationParams struct {
	// Trip ID.
	TripID int
	// Transportation ID.
	TransportationID int
}

// DeleteTripParams is parameters of deleteTrip operation.
type DeleteTripParams struct {
	// Trip ID.
	TripID int
}

// DownloadAttachmentParams is parameters of downloadAttachment operation.
type DownloadAttachmentParams struct {
	// Trip ID.
	TripID int
	// Attachment ID.
	AttachmentID int
}

// GetAccommodationByIDParams is parameters of getAccommodationByID operation.
type GetAccommodationByIDParams struct {
	// Trip ID.
	TripID int
	// Accommodation ID.
	AccommodationID int
}

// GetActivitiesParams is parameters of getActivities operation.
type GetActivitiesParams struct {
	// Trip ID.
	TripID int
}

// GetActivityParams is parameters of getActivity operation.
type GetActivityParams struct {
	// Trip ID.
	TripID int
	// Activity ID.
	ActivityID int
}

// GetAllAccommodationParams is parameters of getAllAccommodation operation.
type GetAllAccommodationParams struct {
	// Trip ID.
	TripID int
}

// GetAllTransportationParams is parameters of getAllTransportation operation.
type GetAllTransportationParams struct {
	// Trip ID.
	TripID int
}

// GetAttachmentsParams is parameters of getAttachments operation.
type GetAttachmentsParams struct {
	// Trip ID.
	TripID int
}

// GetGeoJsonParams is parameters of getGeoJson operation.
type GetGeoJsonParams struct {
	// Trip ID.
	TripID int
}

// GetLocationParams is parameters of getLocation operation.
type GetLocationParams struct {
	// Location query.
	Query string
}

// GetTrainStationParams is parameters of getTrainStation operation.
type GetTrainStationParams struct {
	// Station query.
	Query string
}

// GetTransportationParams is parameters of getTransportation operation.
type GetTransportationParams struct {
	// Trip ID.
	TripID int
	// Transportation ID.
	TransportationID int
}

// GetTripParams is parameters of getTrip operation.
type GetTripParams struct {
	// Trip ID.
	TripID int
}

// GetUserParams is parameters of getUser operation.
type GetUserParams struct {
	// User ID.
	UserID int
}

// PostAccommodationParams is parameters of postAccommodation operation.
type PostAccommodationParams struct {
	// Trip ID.
	TripID int
}

// PostActivityParams is parameters of postActivity operation.
type PostActivityParams struct {
	// Trip ID.
	TripID int
}

// PostAttachmentParams is parameters of postAttachment operation.
type PostAttachmentParams struct {
	// Trip ID.
	TripID int
}

// PostFlightParams is parameters of postFlight operation.
type PostFlightParams struct {
	// Trip ID.
	TripID int
}

// PostTrainJourneyParams is parameters of postTrainJourney operation.
type PostTrainJourneyParams struct {
	// Trip ID.
	TripID int
}

// PostTransportationParams is parameters of postTransportation operation.
type PostTransportationParams struct {
	// Trip ID.
	TripID int
}

// PutAccommodationParams is parameters of putAccommodation operation.
type PutAccommodationParams struct {
	// Trip ID.
	TripID int
	// Accommodation ID.
	AccommodationID int
}

// PutActivityParams is parameters of putActivity operation.
type PutActivityParams struct {
	// Trip ID.
	TripID int
	// Activity ID.
	ActivityID int
}

// PutFlightParams is parameters of putFlight operation.
type PutFlightParams struct {
	// Trip ID.
	TripID int
	// Flight ID.
	FlightID int
}

// PutTransportationParams is parameters of putTransportation operation.
type PutTransportationParams struct {
	// Trip ID.
	TripID int
	// Transportation ID.
	TransportationID int
}

// PutTripParams is parameters of putTrip operation.
type PutTripParams struct {
	// Trip ID.
	TripID int
}
