// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetLocationOperation      OperationName = "GetLocation"
	GetTrainStationOperation  OperationName = "GetTrainStation"
	PostFlightOperation       OperationName = "PostFlight"
	PostTrainJourneyOperation OperationName = "PostTrainJourney"
)
