// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	DeleteAccommodationOperation  OperationName = "DeleteAccommodation"
	DeleteActivityOperation       OperationName = "DeleteActivity"
	DeleteAttachmentOperation     OperationName = "DeleteAttachment"
	DeleteTransportationOperation OperationName = "DeleteTransportation"
	DeleteTripOperation           OperationName = "DeleteTrip"
	DownloadAttachmentOperation   OperationName = "DownloadAttachment"
	GetAccommodationByIDOperation OperationName = "GetAccommodationByID"
	GetActivitiesOperation        OperationName = "GetActivities"
	GetActivityOperation          OperationName = "GetActivity"
	GetAllAccommodationOperation  OperationName = "GetAllAccommodation"
	GetAllTransportationOperation OperationName = "GetAllTransportation"
	GetAttachmentsOperation       OperationName = "GetAttachments"
	GetGeoJsonOperation           OperationName = "GetGeoJson"
	GetLocationOperation          OperationName = "GetLocation"
	GetTrainStationOperation      OperationName = "GetTrainStation"
	GetTransportationOperation    OperationName = "GetTransportation"
	GetTripOperation              OperationName = "GetTrip"
	GetTripsOperation             OperationName = "GetTrips"
	GetUserOperation              OperationName = "GetUser"
	GetUsersOperation             OperationName = "GetUsers"
	PostAccommodationOperation    OperationName = "PostAccommodation"
	PostActivityOperation         OperationName = "PostActivity"
	PostAttachmentOperation       OperationName = "PostAttachment"
	PostFlightOperation           OperationName = "PostFlight"
	PostTrainJourneyOperation     OperationName = "PostTrainJourney"
	PostTransportationOperation   OperationName = "PostTransportation"
	PostTripOperation             OperationName = "PostTrip"
	PutAccommodationOperation     OperationName = "PutAccommodation"
	PutActivityOperation          OperationName = "PutActivity"
	PutFlightOperation            OperationName = "PutFlight"
	PutTransportationOperation    OperationName = "PutTransportation"
	PutTripOperation              OperationName = "PutTrip"
)
