// Code generated by ogen, DO NOT EDIT.
package api

type DeleteAccommodationRes interface {
	deleteAccommodationRes()
}

type DeleteActivityRes interface {
	deleteActivityRes()
}

type DeleteAttachmentRes interface {
	deleteAttachmentRes()
}

type DeleteTransportationRes interface {
	deleteTransportationRes()
}

type DeleteTripRes interface {
	deleteTripRes()
}

type DownloadAttachmentRes interface {
	downloadAttachmentRes()
}

type GetAccommodationByIDRes interface {
	getAccommodationByIDRes()
}

type GetActivitiesRes interface {
	getActivitiesRes()
}

type GetActivityRes interface {
	getActivityRes()
}

type GetAllAccommodationRes interface {
	getAllAccommodationRes()
}

type GetAllTransportationRes interface {
	getAllTransportationRes()
}

type GetAttachmentsRes interface {
	getAttachmentsRes()
}

type GetTransportationRes interface {
	getTransportationRes()
}

type GetTripRes interface {
	getTripRes()
}

type GetTripsRes interface {
	getTripsRes()
}

type GetUserRes interface {
	getUserRes()
}

type GetUsersRes interface {
	getUsersRes()
}

type PostAccommodationRes interface {
	postAccommodationRes()
}

type PostActivityRes interface {
	postActivityRes()
}

type PostAttachmentRes interface {
	postAttachmentRes()
}

type PostFlightRes interface {
	postFlightRes()
}

type PostTripRes interface {
	postTripRes()
}

type PutAccommodationRes interface {
	putAccommodationRes()
}

type PutActivityRes interface {
	putActivityRes()
}

type PutFlightRes interface {
	putFlightRes()
}

type PutTripRes interface {
	putTripRes()
}
