// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: location.sql

package sqlc

import (
	"context"
)

const insertLocation = `-- name: InsertLocation :one
INSERT INTO location (
    latitude, longitude
) VALUES (
    $1, $2
 )
RETURNING id
`

type InsertLocationParams struct {
	Latitude  float32
	Longitude float32
}

func (q *Queries) InsertLocation(ctx context.Context, arg InsertLocationParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertLocation, arg.Latitude, arg.Longitude)
	var id int32
	err := row.Scan(&id)
	return id, err
}
