// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"cloud.google.com/go/civil"
)

type Accommodation struct {
	ID            int32
	TripID        int32
	LocationID    *int32
	Name          string
	ArrivalDate   civil.Date
	DepartureDate civil.Date
	CheckInTime   *civil.Time
	CheckOutTime  *civil.Time
	Description   *string
	Address       *string
	Price         *int32
}

type Activity struct {
	ID          int32
	TripID      int32
	LocationID  *int32
	Name        string
	Date        civil.Date
	Time        *civil.Time
	Description *string
	Address     *string
	Price       *int32
}

type Airport struct {
	Iata         string
	Name         string
	Municipality string
	LocationID   *int32
}

type Attachment struct {
	ID     int32
	TripID int32
	Name   string
	Blob   []byte
}

type AttachmentAccommodation struct {
	AttachmentID    int32
	AccommodationID int32
}

type AttachmentActivity struct {
	AttachmentID int32
	ActivityID   int32
}

type AttachmentTransportation struct {
	AttachmentID     int32
	TransportationID int32
}

type FlightLeg struct {
	ID                int32
	TransportationID  int32
	Origin            string
	Destination       string
	Airline           string
	FlightNumber      string
	DepartureTime     civil.DateTime
	ArrivalTime       civil.DateTime
	DurationInMinutes int32
	Aircraft          *string
}

type FlightPnr struct {
	ID               int32
	TransportationID int32
	Airline          string
	Pnr              string
}

type Location struct {
	ID        int32
	Latitude  float32
	Longitude float32
}

type Transportation struct {
	ID            int32
	TripID        int32
	Type          string
	OriginID      int32
	DestinationID int32
	DepartureTime civil.DateTime
	ArrivalTime   civil.DateTime
	Geojson       []byte
	Price         *int32
}

type Trip struct {
	ID          int32
	Name        string
	StartDate   civil.Date
	EndDate     civil.Date
	Description *string
	ImageUrl    *string
}

type User struct {
	ID   int32
	Name string
}
