// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"cloud.google.com/go/civil"
	null "github.com/guregu/null/v6"
)

type Accommodation struct {
	ID            int32
	TripID        int32
	Name          string
	Description   null.String
	ArrivalDate   civil.Date
	DepartureDate civil.Date
	Location      null.String
	Price         null.Int32
}

type Activity struct {
	ID          int32
	TripID      int32
	Name        string
	Description null.String
	Date        civil.Date
}

type Airport struct {
	Iata         string
	Name         string
	Municipality string
	Location     null.String
}

type Flight struct {
	ID     int32
	TripID int32
	Price  null.Int32
}

type FlightLeg struct {
	ID            int32
	FlightID      int32
	Origin        string
	Destination   string
	Airline       string
	FlightNumber  string
	DepartureTime string
	ArrivalTime   string
	Aircraft      null.String
}

type Pnr struct {
	ID       int32
	FlightID int32
	Airline  string
	Pnr      string
}

type Trip struct {
	ID          int32
	Name        string
	Description null.String
	StartDate   civil.Date
	EndDate     civil.Date
}

type User struct {
	ID   int32
	Name string
}
