// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, jwt_sub
FROM "user"
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.JwtSub)
	return i, err
}

const getUserByJwtSub = `-- name: GetUserByJwtSub :one
SELECT id, name, jwt_sub
FROM "user"
WHERE jwt_sub = $1
`

func (q *Queries) GetUserByJwtSub(ctx context.Context, jwtSub uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByJwtSub, jwtSub)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.JwtSub)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, name, jwt_sub
FROM "user"
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.JwtSub); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasReadPermission = `-- name: HasReadPermission :one
SELECT EXISTS (
    SELECT 1
    FROM trip
             LEFT JOIN permissions p ON trip.id = p.trip_id
    WHERE (trip.owner_id = $1 OR p.user_id = $1)
      AND id = $2
)
`

type HasReadPermissionParams struct {
	UserID int32
	TripID int32
}

func (q *Queries) HasReadPermission(ctx context.Context, arg HasReadPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasReadPermission, arg.UserID, arg.TripID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasWritePermission = `-- name: HasWritePermission :one
SELECT EXISTS (
    SELECT 1
    FROM trip
             LEFT JOIN permissions p ON trip.id = p.trip_id
    WHERE (trip.owner_id = $1 OR (p.user_id = $1 AND p.write is true))
      AND id = $2
)
`

type HasWritePermissionParams struct {
	UserID int32
	TripID int32
}

func (q *Queries) HasWritePermission(ctx context.Context, arg HasWritePermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasWritePermission, arg.UserID, arg.TripID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO "user" (name, jwt_sub)
VALUES ($1, $2)
RETURNING id
`

type InsertUserParams struct {
	Name   string
	JwtSub uuid.UUID
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Name, arg.JwtSub)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const isTripOwner = `-- name: IsTripOwner :one
SELECT EXISTS (
    SELECT 1
    FROM trip
    WHERE trip.owner_id = $1
      AND id = $2
)
`

type IsTripOwnerParams struct {
	UserID int32
	TripID int32
}

func (q *Queries) IsTripOwner(ctx context.Context, arg IsTripOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTripOwner, arg.UserID, arg.TripID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
