// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/trips": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Get all trips",
                "operationId": "getTrips",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Trip"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/trips/{trip_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Get trip by ID",
                "operationId": "getTrip",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Trip"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/trips/{trip_id}/accommodation": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accommodation"
                ],
                "summary": "Get all accommodation",
                "operationId": "getAllAccommodation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Accommodation"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accommodation"
                ],
                "summary": "Add accommodation",
                "operationId": "postAccommodation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "accommodation",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Accommodation"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/trips/{trip_id}/accommodation/{accommodation_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accommodation"
                ],
                "summary": "Get accommodation by ID",
                "operationId": "getAccommodationByID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Accommodation ID",
                        "name": "accommodation_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Accommodation"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accommodation"
                ],
                "summary": "Update accommodation",
                "operationId": "putAccommodation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Accommodation ID",
                        "name": "accommodation_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "accommodation",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Accommodation"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "accommodation"
                ],
                "summary": "Delete accommodation",
                "operationId": "deleteAccommodation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Accommodation ID",
                        "name": "accommodation_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/trips/{trip_id}/activities": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Get all activities",
                "operationId": "getActivities",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Activity"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Add activity",
                "operationId": "postActivity",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "activity",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Activity"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/trips/{trip_id}/activities/{activity_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Get activity by ID",
                "operationId": "getActivity",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity ID",
                        "name": "activity_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Activity"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "Update activity",
                "operationId": "putActivity",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity ID",
                        "name": "activity_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "activity",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Activity"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "activities"
                ],
                "summary": "Delete activity",
                "operationId": "deleteActivity",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Activity ID",
                        "name": "activity_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/trips/{trip_id}/flights": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Get all flights",
                "operationId": "getFlights",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Flight"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Add flight",
                "operationId": "postFlight",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "flight",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Flight"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/trips/{trip_id}/flights/{flight_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Get flight by ID",
                "operationId": "getFlight",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Flight ID",
                        "name": "flight_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Flight"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Update flight",
                "operationId": "putFlight",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Flight ID",
                        "name": "flight_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "flight",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Flight"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "flights"
                ],
                "summary": "Delete flight",
                "operationId": "deleteFlight",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trip ID",
                        "name": "trip_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Flight ID",
                        "name": "flight_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get all users",
                "operationId": "getUsers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.User"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "operationId": "getUser",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Accommodation": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "arrivalDate": {
                    "type": "string"
                },
                "checkInTime": {
                    "type": "string"
                },
                "checkOutTime": {
                    "type": "string"
                },
                "departureDate": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "$ref": "#/definitions/entity.Location"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "tripId": {
                    "type": "integer"
                }
            }
        },
        "entity.Activity": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "$ref": "#/definitions/entity.Location"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                },
                "tripId": {
                    "type": "integer"
                }
            }
        },
        "entity.Airport": {
            "type": "object",
            "properties": {
                "iata": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/entity.Location"
                },
                "municipality": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entity.Flight": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "legs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.FlightLeg"
                    }
                },
                "pnrs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.PNR"
                    }
                },
                "price": {
                    "type": "integer"
                },
                "tripId": {
                    "type": "integer"
                }
            }
        },
        "entity.FlightLeg": {
            "type": "object",
            "properties": {
                "aircraft": {
                    "type": "string"
                },
                "airline": {
                    "type": "string"
                },
                "arrivalDateTime": {
                    "type": "string"
                },
                "departureDateTime": {
                    "type": "string"
                },
                "destination": {
                    "$ref": "#/definitions/entity.Airport"
                },
                "durationInMinutes": {
                    "type": "integer"
                },
                "flightNumber": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "origin": {
                    "$ref": "#/definitions/entity.Airport"
                }
            }
        },
        "entity.Location": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "entity.PNR": {
            "type": "object",
            "properties": {
                "airline": {
                    "type": "string",
                    "example": "LH"
                },
                "id": {
                    "type": "integer"
                },
                "pnr": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "entity.Trip": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                }
            }
        },
        "entity.User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "request.Accommodation": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "arrivalDate": {
                    "type": "string"
                },
                "checkInTime": {
                    "type": "string"
                },
                "checkOutTime": {
                    "type": "string"
                },
                "departureDate": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/entity.Location"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                }
            }
        },
        "request.Activity": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/entity.Location"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "request.Flight": {
            "type": "object",
            "required": [
                "legs",
                "pnrs"
            ],
            "properties": {
                "legs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.FlightLeg"
                    }
                },
                "pnrs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.PNR"
                    }
                },
                "price": {
                    "type": "integer"
                }
            }
        },
        "request.FlightLeg": {
            "type": "object",
            "required": [
                "date",
                "flightNumber"
            ],
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2026-01-30"
                },
                "flightNumber": {
                    "type": "string",
                    "example": "EK412"
                },
                "originAirport": {
                    "type": "string",
                    "example": "SYD"
                }
            }
        },
        "response.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "message"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "TravelPlanner API",
	Description:      "Using a translation service as an example",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
