basePath: /api/v1
definitions:
  entity.Accommodation:
    properties:
      address:
        type: string
      arrivalDate:
        type: string
      checkInTime:
        type: string
      checkOutTime:
        type: string
      departureDate:
        type: string
      description:
        type: string
      id:
        type: integer
      location:
        $ref: '#/definitions/entity.Location'
      name:
        type: string
      price:
        type: integer
      tripId:
        type: integer
    type: object
  entity.Activity:
    properties:
      address:
        type: string
      date:
        type: string
      description:
        type: string
      id:
        type: integer
      location:
        $ref: '#/definitions/entity.Location'
      name:
        type: string
      price:
        type: integer
      time:
        type: string
      tripId:
        type: integer
    type: object
  entity.Airport:
    properties:
      iata:
        type: string
      location:
        $ref: '#/definitions/entity.Location'
      municipality:
        type: string
      name:
        type: string
    type: object
  entity.Flight:
    properties:
      id:
        type: integer
      legs:
        items:
          $ref: '#/definitions/entity.FlightLeg'
        type: array
      pnrs:
        items:
          $ref: '#/definitions/entity.PNR'
        type: array
      price:
        type: integer
      tripId:
        type: integer
    type: object
  entity.FlightLeg:
    properties:
      aircraft:
        type: string
      airline:
        type: string
      arrivalDateTime:
        type: string
      departureDateTime:
        type: string
      destination:
        $ref: '#/definitions/entity.Airport'
      durationInMinutes:
        type: integer
      flightNumber:
        type: string
      id:
        type: integer
      origin:
        $ref: '#/definitions/entity.Airport'
    type: object
  entity.Location:
    properties:
      id:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
    type: object
  entity.PNR:
    properties:
      airline:
        example: LH
        type: string
      id:
        type: integer
      pnr:
        example: "123456"
        type: string
    type: object
  entity.Trip:
    properties:
      description:
        type: string
      endDate:
        type: string
      id:
        type: integer
      name:
        type: string
      startDate:
        type: string
    type: object
  entity.User:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  request.Accommodation:
    properties:
      address:
        type: string
      arrivalDate:
        type: string
      checkInTime:
        type: string
      checkOutTime:
        type: string
      departureDate:
        type: string
      description:
        type: string
      location:
        $ref: '#/definitions/entity.Location'
      name:
        type: string
      price:
        type: integer
    type: object
  request.Activity:
    properties:
      address:
        type: string
      date:
        type: string
      description:
        type: string
      location:
        $ref: '#/definitions/entity.Location'
      name:
        type: string
      price:
        type: integer
      time:
        type: string
    type: object
  request.Flight:
    properties:
      legs:
        items:
          $ref: '#/definitions/request.FlightLeg'
        type: array
      pnrs:
        items:
          $ref: '#/definitions/entity.PNR'
        type: array
      price:
        type: integer
    required:
    - legs
    - pnrs
    type: object
  request.FlightLeg:
    properties:
      date:
        example: "2026-01-30"
        type: string
      flightNumber:
        example: EK412
        type: string
      originAirport:
        example: SYD
        type: string
    required:
    - date
    - flightNumber
    type: object
  response.Error:
    properties:
      error:
        example: message
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: Using a translation service as an example
  title: TravelPlanner API
  version: "1.0"
paths:
  /trips:
    get:
      operationId: getTrips
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Trip'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Get all trips
      tags:
      - trips
  /trips/{trip_id}:
    get:
      operationId: getTrip
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Trip'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Get trip by ID
      tags:
      - trips
  /trips/{trip_id}/accommodation:
    get:
      operationId: getAllAccommodation
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Accommodation'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Get all accommodation
      tags:
      - accommodation
    post:
      consumes:
      - application/json
      operationId: postAccommodation
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      - description: accommodation
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Accommodation'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Add accommodation
      tags:
      - accommodation
  /trips/{trip_id}/accommodation/{accommodation_id}:
    delete:
      operationId: deleteAccommodation
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      - description: Accommodation ID
        in: path
        name: accommodation_id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Delete accommodation
      tags:
      - accommodation
    get:
      operationId: getAccommodationByID
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      - description: Accommodation ID
        in: path
        name: accommodation_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Accommodation'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Get accommodation by ID
      tags:
      - accommodation
    put:
      consumes:
      - application/json
      operationId: putAccommodation
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      - description: Accommodation ID
        in: path
        name: accommodation_id
        required: true
        type: string
      - description: accommodation
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Accommodation'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Update accommodation
      tags:
      - accommodation
  /trips/{trip_id}/activities:
    get:
      operationId: getActivities
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Activity'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Get all activities
      tags:
      - activities
    post:
      consumes:
      - application/json
      operationId: postActivity
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      - description: activity
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Activity'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Add activity
      tags:
      - activities
  /trips/{trip_id}/activities/{activity_id}:
    delete:
      operationId: deleteActivity
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      - description: Activity ID
        in: path
        name: activity_id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Delete activity
      tags:
      - activities
    get:
      operationId: getActivity
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      - description: Activity ID
        in: path
        name: activity_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Activity'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Get activity by ID
      tags:
      - activities
    put:
      consumes:
      - application/json
      operationId: putActivity
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      - description: Activity ID
        in: path
        name: activity_id
        required: true
        type: string
      - description: activity
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Activity'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Update activity
      tags:
      - activities
  /trips/{trip_id}/flights:
    get:
      operationId: getFlights
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Flight'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Get all flights
      tags:
      - flights
    post:
      consumes:
      - application/json
      operationId: postFlight
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      - description: flight
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Flight'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Add flight
      tags:
      - flights
  /trips/{trip_id}/flights/{flight_id}:
    delete:
      operationId: deleteFlight
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      - description: Flight ID
        in: path
        name: flight_id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Delete flight
      tags:
      - flights
    get:
      operationId: getFlight
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      - description: Flight ID
        in: path
        name: flight_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Flight'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Get flight by ID
      tags:
      - flights
    put:
      consumes:
      - application/json
      operationId: putFlight
      parameters:
      - description: Trip ID
        in: path
        name: trip_id
        required: true
        type: integer
      - description: Flight ID
        in: path
        name: flight_id
        required: true
        type: string
      - description: flight
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Flight'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Update flight
      tags:
      - flights
  /users:
    get:
      operationId: getUsers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Get all users
      tags:
      - users
  /users/{user_id}:
    get:
      operationId: getUser
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Get user by ID
      tags:
      - users
swagger: "2.0"
